<?php namespace esoTalk;

use Session;

class Page {

	/**
	 * An array of data to pass to the page via the 'ET' JavaScript variable.
	 * 
	 * @var array
	 */
	protected static $data = array();
	
	/**
	 * Set a variable that can be accessed by JavaScript code on the page,
	 * as a property of the ET object.
	 *
	 * @param  string $key  The key to make $val accessible under.
	 * @param  mixed  $val  The value.
	 * @return void
	 */
	public static function data($key, $val)
	{
		static::$data[$key] = $val;
	}


	public static function head($val)
	{

	}

	public static function get_head()
	{
		$head = '<!-- This page was generated by esoTalk (http://esotalk.org) -->'.PHP_EOL;

		$head .= '<meta charset="'.T('general.charset', 'utf-8').'">'.PHP_EOL;

		$head .= '<title>'.static::get_title().'</title>'.PHP_EOL;

		// Add the canonical URL tag.
		if ( ! empty(static::$canonical_url))
			$head .= '<link rel="canonical" href="'.static::$canonical_url.'">'.PHP_EOL;

		$head .= Asset::container('global')->styles();
		$head .= Asset::container('default')->styles();
		$head .= Asset::container('global')->scripts();
		$head .= Asset::container('default')->scripts();

		// Output all necessary config variables and language definitions, as well as other variables.
		// $esoTalkJS = array(
		// 	"webPath" => ET::$webPath,
		// 	"userId" => ET::$session->user ? (int)ET::$session->userId : false,
		// 	"token" => ET::$session->token,
		// 	"debug" => C("esoTalk.debug"),
		// 	"language" => $this->jsLanguage
		// ) + (array)$this->jsData;
		// $head .= "<script>var ET=".json_encode($esoTalkJS)."</script>";

		return $head;
	}

	protected static $title = '';

	public static function title($title)
	{
		static::$title = $title;
	}

	public static function get_title()
	{
		$parts = array(static::$title, C('esoTalk.forum_title'));

		return implode(' - ', Arr::without($parts, ''));
	}

	protected static $canonical_url;

	public static function canonical_url($url)
	{
		static::$canonical_url = $url;
	}

	public static function navigate()
	{
		
	}

	public static function get_back_button()
	{
		
	}

	public static function get_logo()
	{
		$logo = C('esoTalk.forum_logo');
		$title = C('esoTalk.forum_title');
		if ($logo)
		{
			$size = getimagesize($logo);
			return HTML::image($logo, $title, array('width' => $size[0], 'height' => $size[1]));
		}
		else
		{
			return $title;
		}
	}


	private $messages = array();
	
	/**
	 * Add a message to be displayed on the page. The messages will also be stored in the session so that if the
	 * controller redirects instead of rendering, they will be displayed on the next response.
	 *
	 * @param string $message The message text.
	 * @param mixed $options An array of options. Possible keys include:
	 * 		id: a unique ID for the message. If specified, this message will overwrite any previous messages with
	 * 			the same ID.
	 * 		className: the CSS class to apply to the message.
	 * 		callback: a JavaScript function to run when the message is dismissed.
	 * 		If $options is a string, it will be used as the className.
	 * @return void
	 */
	public static function flash($message, $options = "")
	{
		if ( ! is_array($options))
		{
			$options = array("className" => $options);
		}

		$options["message"] = $message;

		if ( ! empty($options["id"]))
		{
			$this->messages[$options["id"]] = $options;
		}
		else
		{
			$this->messages[] = $options;
		}

		Session::flash('messages', $this->messages);
	}

	public static function get_flash()
	{
		return Session::get('messages', array());
	}

}